### ISSUE TITLE
Any interest to include datasets?

### ISSUE THREAD

**Issue by kirbyju** [open-dicom/awesome-dicom#17]
Hi, I am wondering if it might be good to also include a list of databases/datasets so that people can easily find sample DICOM data to work with when trying out all these other resources.  This is somewhat self serving, as I'd love to make sure everyone knows about https://www.cancerimagingarchive.net/ that my team manages, but it's truly an awesome source of all kinds of DICOM data :-)

**Comment by neurolabusc** [comment]
At one stage, I tried to keep a [list](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Sample_DICOM_Images), though I think some of the links are dead. Happy to see these incorporated in a maintained resource.

**Comment by zvi-quantivly** [comment]
Absolutely. Please don't hesitate to make a PR. I can also try to come up with something, but it will probably take me some time. 
Thank you! 🙏🏼

**Comment by ZviBaratz** [comment]
Absolutely. Please don't hesitate to make a PR. I can also try to come up with something, but it will probably take me some time.
Thank you! 🙏🏼

**Comment by kirbyju** [comment]
Just submitted one.
